# num1=int(input("enter num1"))
# num2=int(input("enter num2"))
# print("addition=",num1+num2)
# print("substration=",num1-num2)
# print("multiplication",num1*num2)
# print("division=",num1/num2)
# print("modulus=",num1%num2)
# print("exponention=",num1**num2)
# print("floor division=",num1//num2)
